---
title: "Check project"
author: "Stephan.Huber@hs-fresenius.de"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
    number_sections: yes
  html_document:
    toc: yes
    toc_depth: 2
    number_sections: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    fig_caption: true
header-includes: \usepackage{setspace}\doublespacing
fontsize: 12pt
urlcolor: blue
linkcolor: red
bibliography: ../lit/references.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-6th-edition.csl"
---

```{r, echo=FALSE}
setwd("~/Dropbox/hsf/github/courses/rmd")
```


Word count (alternative): `r as.integer(sub("(\\d+).+$", "\\1", system(sprintf("wc -w %s", knitr::current_input()), intern = TRUE))) - 20`


# Affidavit

I hereby affirm that this submitted paper was authored unaided and
solely by me. Additionally, no other sources than those in the reference
list were used. Parts of this paper, including tables and figures, that
have been taken either verbatim or analogously from other works have in
each case been properly cited with regard to their origin and
authorship. This paper either in parts or in its entirety, be it in the
same or similar form, has not been submitted to any other examination
board and has not been published.

I have read the Handbook of Academic Writing by @Hildebrandt2019Handbook and
have endeavored to comply with the guidelines and standards set forth
therein.

I acknowledge that the university may use plagiarism detection software
to check my thesis. I agree to cooperate with any investigation of
suspected plagiarism and to provide any additional information or
evidence requested by the university.

I assure the project report contains the following:



-   [ ] The report is written in R Markdown.

The report contains...

- [ ] ... 5000-6000 words.

- [ ] ... a title and personal detail (name, email, matriculation
    number).

- [ ] ... a word count.

- [ ] ... an abstract.

- [ ] ... a bibliography that was created using BibTeX applying an APA
    citation style.

- [ ] ... the complete R code that is necessary to replicate your
    results.

- [ ] ... detailed information on how the data are downloaded and read
    in to R.

- [ ] ... an introduction where you guide the reader and a conclusion
    where you summarize your work and discuss what you would work on if
    you would have more time available.

- [ ] ... all significant resources that were used to write the report
    and the R code.

- [ ] ...a brief description of the successful contribution using Git and GitHub as explained here: [https://github.com/hubchev/ds_summer23](https://github.com/hubchev/ds_summer23).


The submission of the project contains 

- [ ] ... the .Rmd file of the
report. 
- [ ] ... the .pdf format of the report. 
- [ ] ... the .html format of the report. 
- [ ] ... all files necessary that are not available online to reproduce the report and the R code therein.
- [ ] ... 
- [ ] ... 
- [ ] ... 
- [ ] ... 
- [ ] ...


# References